---
title: "Performance Summary"
date: "`r params$reportdate`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
    vertical_layout: fill
params:
  dateStart: "2002-01-02"
  dynamictitle: "My report"
  reportdate: !r Sys.Date()
  symbols: "SPL.AX"
  ticker: "SPL.AX"
runtime: shiny
theme: spacelab
---

```{r global, echo=FALSE, include=FALSE, message = FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
knitr::opts_knit$set(root.dir = "..", echo = FALSE)
library(data.table)
library(dplyr)
library(DT)
library(dygraphs)
library(flexdashboard)
library(formattable)
library(highcharter)
library(hydroTSM)
library(PerformanceAnalytics)
library(plotly)
library(quantmod)
library(rmarkdown)
library(scales)
library(shiny)
library(shinydashboard)
library(tidyquant)
library(tidyverse)
library(timetk)
library(treemap)
library(utils)
library(xts)
library(zoo)

```

```{r functions}

# A function to build an xts object to hold both ticker returns.
sector_correlations <- function(sector, period = "weeks", window = 10) {

prices <- getSymbols("SPL.AX", src = 'yahoo', 
          from = format(input$dateRange[1]),
          to = format(input$dateRange[2]),
          auto.assign = TRUE, warnings = FALSE) %>% 
          map(~Ad(get(.))) %>% 
          reduce(merge)

prices_period <- to.period(prices, period = period, OHLC = FALSE)
# get monthly log returns
returns <-na.omit(ROC(prices_period, 1, type = "continuous"))
# change date format
index(returns) <- as.Date(as.yearmon(index(returns), format = '%Y%m'))

returns$rolling_cor <- rollapply(returns, window, 
                                 function(x) 
                                 cor(x[, 1], x[, 2], use = "pairwise.complete.obs"), 
                                 by.column = FALSE)

# We care about the name because it will be displayed in the dygraph when a user hovers.

names(returns) <- c(paste(sector, "Returns", sep = ""), "SPY Returns", paste(sector, "/SPY Correlation", sep = ""))

assign("sector_correlations", returns, .GlobalEnv)
}

# Function to calculate monthly returns on a stock
monthly_stock_returns <- function(ticker, dateStart) {
  # Download the data from Yahoo finance
  symbol <- getSymbols("SPL.AX", src = 'yahoo', from = "2019-07-02",
                       auto.assign = FALSE, warnings = FALSE)
  # Tranform it to monthly returns using the periodReturn function from quantmod
  data <- periodReturn("SPL.AX", period = 'monthly', type = 'log')

  # Let's rename the column of returns to something intuitive because the column
  # name is what will eventually be displayed on the time series graph
  colnames(data) <- as.character("SPL.AX")

  # We want to be able to work with the xts objects that result from this function
  # so let's explicitly put them to the global environment with an easy to use
  # name, the stock ticker
  assign("SPL_returns", data, .GlobalEnv)
}

```

Page 1
=====================================  

Input {.sidebar}
-------------------------------------
  
```{r sidebarInput}

dateRangeInput("dateRange",
               "Historical data",
               start = params$dateStart,
               end   = Sys.Date())

actionButton("go", "Submit")

```

```{r sidebarActionGo}
# We will use this in the value box after the submit button is activated

prices <- eventReactive(input$go, {

  prices <- 
    getSymbols("SPL.AX", src = 'yahoo', 
               from = format(input$dateRange[1]), 
               to = format(input$dateRange[2]),
               auto.assign = TRUE, 
               warnings = FALSE) %>% 
    map(~Cl(get(.))) %>% 
    reduce(merge)

})

tqPrices <- eventReactive(input$go, {
  
  tqPrices <- tq_get("SPL.AX", 
              get = "stock.prices",
              from = format(input$dateRange[1]),
              to = format(input$dateRange[2])) 
})


xprices <- eventReactive(input$go, {
  
  symbols <- c(params$symbols, "^IRX")
  
  tq_get(symbols, 
         get = "stock.prices",
         from = input$dateRange[1],
         to = input$dateRange[2])
    
})

portfolio_returns_xts <- eventReactive(input$go, {
  prices <- prices()
  
  w <- c("SPL.AX")

  prices_monthly <- to.monthly(prices, indexAt = "last", OHLC = FALSE)
  
  asset_returns_xts <- na.omit(Return.calculate(prices_monthly, method = "log"))
  
  portfolio_returns_xts <- 
    Return.portfolio(asset_returns_xts, weights = w) %>% 
    `colnames<-`("returns")
})  


price <- reactive({tq_get("SPL.AX", from = format(input$dateRange[1]), to = format(input$dateRange[2])) %>% 
  mutate(change = close - open)})
```

Row {data-height=50}
-------------------------------------

### Number of Calendar Days

```{r vbox-calendar-days}

valueBoxOutput("approvalBox1")

output$approvalBox1<-renderValueBox({
  xts_price <- tk_xts(price())
  colnames(xts_price) <- paste0(input$ticker,'.', colnames(xts_price))
  calendarDays <- end(xts_price)-start(xts_price)
  
  valueBox("",
      format(calendarDays, big.mark = ","),
      color = "teal"
#    icon = 'ion-cash'
  )
})
#xts_price <- tk_xts(price())
#calendarDays <- end(xts_price)-start(xts_SPL.AX)
#cd <- readRDS("calendarDays.rds")

#flexdashboard::valueBox(paste(format(cd, big.mark = ","), ""), caption = "# of Calendar Days", icon="fa-pencil")
#flexdashboard: valueBox(paste(format(ndays(prices), big.mark = ","), "days"), caption = "# of Trade Days", icon="fa-pencil")

#renderValueBox({
#  calendarDays <- end(xts_price)-start(xts_price)
#  
#valueBox(
#paste(format(calendarDay, big.mark = ","), ""), 
#caption = "# of Calendar Days", 
#icon="fa-pencil"
#)
#})

```

### Percent Return

```{r vbox-returns}

flexdashboard::renderValueBox({
  xts_price <- tk_xts(price())
  #colnames(xts_price) <- paste0(input$ticker,'.', colnames(xts_price))
  cumReturn <- percent((as.numeric(last(xts_price[,4])) - as.numeric(first(xts_price[,4]))) / (as.numeric(first(xts_price[,4]))))

  flexdashboard::valueBox(
      "Percent Return",
      as.character(cumReturn),
#      color = "purple"
      color = ifelse(cumReturn > 0, "green", "red")
#    icon = 'ion-cash'
  )
})



```

### Gauge 1.1
    
```{r}
flexdashboard::renderGauge({
  xts_price <- tk_xts(price())
  cumReturn <- (as.numeric(last(xts_price[,4])) - as.numeric(first(xts_price[,4]))) / (as.numeric(first(xts_price[,4])))
  
    gauge(cumReturn, min = -100, max = 100, symbol = "%") 
  })
```


### Number of Trade Days

```{r vbox-trade-days}
#td <- readRDS("tradeDays.rds")
#flexdashboard::valueBox(paste(format(td, big.mark = ","), "trading days"), caption = "# of Trade Days", icon="fa-pencil")
#flexdashboard::valueBox(paste(td, "days", sep = " "), icon="fa-pencil")
renderValueBox({
  xts_price <- tk_xts(price())
  colnames(xts_price) <- paste0(input$ticker,'.', colnames(xts_price))
  tradeDays <- ndays(xts_price)
  
  valueBox("",
      paste(format(tradeDays, big.mark = ","), " days")
#      icon = icon("credit-card")
#    icon = 'ion-cash'
  )
})
```

Row {data-height=500}
-------------------------------------
### Stock Price Over Time (Chart)
```{r chartPrice, eval=price}
renderHighchart({
  xts_price <- tk_xts(price())
  colnames(xts_price) <- paste0(input$ticker,'.', colnames(xts_price))
  highchart(type = "stock") %>% 
    hc_add_series(xts_price, type = "candlestick")
})

```

Page 2
=====================================     

Column {}
-------------------------------------

### Stock Price Table

```{r tablePrice}
DT::renderDataTable({
  DT::datatable(price(), rownames = FALSE, options = list(order = list(list(0, 'desc')))) %>% 
    formatCurrency(c('open', 'high', 'low', 'close', 'adjusted', 'change')) %>% 
    formatDate(c('date')) %>%
    formatStyle('volume', 
      background = styleColorBar(price()$volume, 'steelblue')
    ) %>% 
    formatStyle(
      'change', 
      color = styleInterval(c(0), c('maroon', 'darkgreen'))
    )  
})
```

Page 3
=====================================     

Column {}
-------------------------------------

### Gauge 3.1
    
```{r}
flexdashboard::renderGauge({
    gauge(60, min = 0, max = 100, symbol = "%") 
  })
```

Column {data-width=500}
-----------------------------------------------------------------------

### Stock Volatility

```{r eval=prices}
renderHighchart({
  
  colnames(prices) <- paste0("SPL.AX",'.', colnames(prices))
  highchart(type = "stock") %>% 
    hc_add_series(prices, type = "candlestick")
})
  
```
