---
title: "Performance Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: embed
runtime: shiny
theme: spacelab
---

```{r global, echo=FALSE, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
knitr::opts_knit$set(root.dir = "..", echo = FALSE)
library(data.table)
library(dplyr)
library(DT)
library(dygraphs)
library(flexdashboard)
library(formattable)
library(highcharter)
library(hydroTSM)
library(PerformanceAnalytics)
library(plotly)
library(quantmod)
library(rmarkdown)
library(scales)
library(shiny)
library(shinydashboard)
library(tidyquant)
library(treemap)
library(utils)
library(xts)
library(zoo)
```

```{r}
SPL <- tq_get("SPL.AX")                                                         # Get TidyQuant Stock Prices
SPL<-SPL[complete.cases(SPL),]
```


Page 1
=====================================  

Input {.sidebar}
-------------------------------------

```{r}
# shiny inputs defined here
sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)
selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

dateRangeInput("daterange1", "Date range:",
                 start = "2001-01-01",
                 end   = "2010-12-31")

# Default start and end is the current date in the client's time zone
dateRangeInput("daterange2", "Date range:")

# start and end are always specified in yyyy-mm-dd, even if the display
# format is different
dateRangeInput("daterange3", "Date range:",
                start  = "2001-01-01",
                end    = "2010-12-31",
                min    = "2001-01-01",
                max    = "2012-12-21",
                format = "mm/dd/yy",
                separator = " - ")

# Pass in Date objects
dateRangeInput("daterange4", "Date range:",
                start = Sys.Date()-10,
                end = Sys.Date()+10)

# Use different language and different first day of week
dateRangeInput("daterange5", "Date range:",
                language = "de",
                weekstart = 1)

# Start with decade view instead of default month view
dateRangeInput("daterange6", "Date range:",
                startview = "decade")
  
inputPanel(radioButtons("category",label= "Select  Category",choices=c("diffPts","diffGF","diffGA","diffGD","diffpos"),inline = TRUE))

selectInput("dataset","Choose :", 
              choices = c("ezce","efzf","zef")) 
```

Row {data-height=50}
-------------------------------------
### Number of Calendar Days


```{r vbox-calendar-days, eval=SPL}
SPL[1,1]
```

### Number of Trade Days

```{r vbox-trade-days}
```

Row {data-height=650}
-------------------------------------
### Chart 4
```{r}
```
Page 2
=====================================     

### Chart 2.1
    
```{r}
```