---
title: "Capm Beta"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---


```{r setup, message = FALSE}
library(tidyverse)
library(highcharter)
library(tidyquant)
library(timetk)
library(scales)
library(broom)
library(highcharter)
```

Sidebar {.sidebar}
=====================================
  
```{r}

fluidRow(
  column(6,
  textInput("stock1", "Stock 1", "SPY")),
  column(5,
  numericInput("w1", "Portf. %", 25, min = 1, max = 100))
)  

fluidRow(
  column(6,
  textInput("stock2", "Stock 2", "EFA")),
  column(5,
  numericInput("w2", "Portf. %", 25, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock3", "Stock 3", "IJS")),
  column(5,
  numericInput("w3", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock4", "Stock 4", "EEM")),
  column(5,
  numericInput("w4", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock5", "Stock 5", "AGG")),
  column(5,
  numericInput("w5", "Portf. %", 10, min = 1, max = 100))
)

fluidRow(
  column(7,
  dateInput("date", "Starting Date", "2013-01-01", format = "yyyy-mm-dd"))
)

actionButton("go", "Submit")
```


```{r}
prices <- eventReactive(input$go, {
  
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5)
  
  getSymbols(symbols, src = 'yahoo', from = input$date, 
             auto.assign = TRUE, warnings = FALSE) %>% 
  map(~Ad(get(.))) %>% 
  reduce(merge) %>%
  `colnames<-`(symbols)
})


market_return <- eventReactive(input$go, {
  market_return <- 
    getSymbols("SPY", src = 'yahoo', from = input$date, 
             auto.assign = TRUE, warnings = FALSE) %>% 
    map(~Ad(get(.))) %>% 
    reduce(merge) %>%
    `colnames<-`("SPY") %>% 
    to.monthly(indexAt = "lastof", OHLC = FALSE) %>% 
    tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
    mutate(returns = (log(SPY) - log(lag(SPY)))) %>% 
    na.omit() %>%
    select(date, returns)
})


portfolio_returns_tq_rebalanced_monthly <- eventReactive(input$go, {
  
  prices <- prices()
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  portfolio_returns_tq_rebalanced_monthly <- 
      prices %>% 
      to.monthly(indexAt = "lastof", OHLC = FALSE) %>% 
      tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
      gather(asset, returns, -date) %>% 
      group_by(asset) %>%  
      mutate(returns = (log(returns) - log(lag(returns)))) %>% 
      na.omit() %>%
      tq_portfolio(assets_col  = asset, 
               returns_col = returns,
               weights     = w,
               col_rename  = "returns",
               rebalance_on = "months")
})

beta_dplyr_byhand <- eventReactive(input$go, {
  
  #portfolio_returns_tq_rebalanced_monthly <- portfolio_returns_tq_rebalanced_monthly()
  
  market_return <- market_return()
  
beta_dplyr_byhand <- 
  portfolio_returns_tq_rebalanced_monthly() %>% 
  do(model = lm(returns ~ market_return$returns, data = .))
  
})
  
portfolio_model_augmented <- eventReactive(input$go, {
  
  portfolio_returns_tq_rebalanced_monthly <- portfolio_returns_tq_rebalanced_monthly()
  
  beta_dplyr_byhand() %>% 
  augment(model) %>% 
  rename(mkt_rtns = market_return.returns) %>% 
  select(returns, mkt_rtns, .fitted) %>% 
  mutate(date = portfolio_returns_tq_rebalanced_monthly$date)
  
})

```

Click submit to calculate the CAPM Beta of your portfolio
=====================================  

Row {data-height=650}
-----------------------------------------------------------------------

### CAPM Highcharter

```{r}
renderHighchart({

portfolio_model_augmented <- portfolio_model_augmented()

highchart() %>% 
  hc_title(text = "Scatter with Regression Line") %>% 
  hc_add_series(portfolio_model_augmented, 
                type = "scatter",
                color = "cornflowerblue",
                hcaes(x = round(mkt_rtns, 4), 
                      y = round(returns, 4),
                      date = date), 
                name = "Returns") %>%
  hc_add_series(portfolio_model_augmented, 
                type = "line", 
                enableMouseTracking = FALSE,
                hcaes(x = mkt_rtns, y = .fitted), 
                name = "CAPM Beta = Slope of Line") %>% 
  hc_xAxis(title = list(text = "Market Returns")) %>% 
  hc_yAxis(title = list(text = "Portfolio Returns")) %>% 
  hc_tooltip(formatter = JS("function(){
     return ('port return: ' + this.y + '  mkt return: ' + this.x +  
     '  date: ' + this.point.date)}"))%>% 
  hc_add_theme(hc_theme_flat()) %>%
  hc_exporting(enabled = TRUE)


})
```


Row 2 {data-height=350}
----------------------------------

### Model Results

```{r}
renderTable({
  beta_dplyr_byhand() %>% 
  tidy(model) %>% 
  mutate(term = c("alpha", "beta"))
}, digits = 4)
```