---
title: "Volatility Contribution"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---


```{r setup, include=FALSE}
library(tidyverse)
library(tidyquant)
library(highcharter)
library(timetk)
library(scales)

```

Volatility
===========================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

```{r}

fluidRow(
  column(6,
  textInput("stock1", "Stock 1", "SPY")),
  column(5,
  numericInput("w1", "Portf. %", 25, min = 1, max = 100))
)  

fluidRow(
  column(6,
  textInput("stock2", "Stock 2", "EFA")),
  column(5,
  numericInput("w2", "Portf. %", 25, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock3", "Stock 3", "IJS")),
  column(5,
  numericInput("w3", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock4", "Stock 4", "EEM")),
  column(5,
  numericInput("w4", "Portf. %", 20, min = 1, max = 100))
)

fluidRow(
  column(6,
  textInput("stock5", "Stock 5", "AGG")),
  column(5,
  numericInput("w5", "Portf. %", 10, min = 1, max = 100))
)


fluidRow(
  column(7,
  dateInput("date", "Starting Date", "2013-01-01", format = "yyyy-mm-dd"))
)

fluidRow(
  column(5,
  numericInput("window", "Window", 12, min = 3, max = 36, step = 1))
)

actionButton("go", "Submit")

```

```{r, message = FALSE, warning = FALSE}

component_contr_matrix_fun <- function(returns, w){
# create covariance matrix
covariance_matrix <- 
  cov(returns)
# calculate portfolio standard deviation
sd_portfolio <- 
  sqrt(t(w) %*% covariance_matrix %*% w)
# calculate marginal contribution of each asset
marginal_contribution <- 
  w %*% covariance_matrix / sd_portfolio[1, 1]
# multiply marginal by weights vecotr
component_contribution <- 
  marginal_contribution * w 
# divide by total standard deviation to get percentages
component_percentages <- 
  component_contribution / sd_portfolio[1, 1] 

component_percentages %>% 
  as_tibble() %>% 
  gather(asset, contribution)
}


interval_sd_by_hand <- 
  function(returns_df, 
           start = 1, 
           window = 24, 
           weights){
  
  # First create start date. 
  start_date <- 
    returns_df$date[start]
  
  # Next an end date that depends on start date and window.
  end_date <-  
    returns_df$date[c(start + window)]
  
  # Filter on start and end date.
  returns_to_use <- 
    returns_df %>% 
    filter(date >= start_date & date < end_date) %>% 
    select(-date)
  
  # Portfolio weights.
  w <- weights

  # Call our original custom function. 
  # We are nesting one function inside another.
  component_percentages <- 
   component_contr_matrix_fun(returns_to_use, w)
  
  # Add back the end date as date column
  results_with_date <- 
    component_percentages %>% 
    mutate(date = ymd(end_date)) %>%
    select(date, everything()) %>% 
    spread(asset, contribution) %>% 
    mutate_if(is.numeric, function(x) x * 100)
}


asset_returns_dplyr_byhand <- eventReactive(input$go, {
  
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5)
  
  prices <- 
    getSymbols(symbols, src = 'yahoo', from = input$date, 
               auto.assign = TRUE, warnings = FALSE) %>% 
    map(~Ad(get(.))) %>% 
    reduce(merge) %>%
    `colnames<-`(symbols)

  
  asset_returns_dplyr_byhand <- 
    prices %>% 
    to.monthly(indexAt = "last", OHLC = FALSE) %>% 
    tk_tbl(preserve_index = TRUE, rename_index = "date") %>%
    gather(asset, returns, -date) %>%
    group_by(asset) %>% 
    mutate(returns = (log(returns) - log(lag(returns)))) %>%
    spread(asset, returns) %>% 
    select(date, symbols) %>% 
    slice(-1)
})

percentages_tibble_pre_built <- eventReactive(input$go, {
  
  asset_returns_xts <- 
    asset_returns_dplyr_byhand() %>% 
    tk_xts(date_col = date)
  
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
  portfolio_vol_comp_contr_total_builtin <- 
    StdDev(asset_returns_xts, 
           weights = w,
           portfolio_method = "component")
  
  symbols <- c(input$stock1, input$stock2, input$stock3, input$stock4, input$stock5)
  
  percentages_tibble_pre_built <- 
    portfolio_vol_comp_contr_total_builtin$pct_contrib_StdDev %>%
    tk_tbl(preserve_index = FALSE) %>%
    mutate(asset = symbols) %>%
    rename('risk contribution' = data) %>%
    mutate(`risk contribution` = round(`risk contribution`, 4) * 100, 
           weights = w * 100) %>% 
    select(asset, everything())
  
})

portfolio_vol_components_xts <- eventReactive(input$go, {
  
  asset_returns_dplyr_byhand <- asset_returns_dplyr_byhand()
  
  w <- c(input$w1/100, input$w2/100, input$w3/100, input$w4/100, input$w5/100)
  
portfolio_vol_components_tidy_by_hand <- 
  map_df(1:(nrow(asset_returns_dplyr_byhand) - input$window), 
         interval_sd_by_hand, 
         returns_df = asset_returns_dplyr_byhand, 
         weights = w, 
         window = input$window) %>% 
  tk_xts(date_col = date)
})

```

Row 1 {.tabset}
-----------------------------------------

### Asset Contribution Highcharter

```{r}
renderHighchart({

  portfolio_vol_components <- 
    portfolio_vol_components_xts()
  
  highchart(type = "stock") %>% 
    hc_title(text = "Volatility Contribution") %>%
    hc_add_series(portfolio_vol_components[, 1], 
                  name = names(portfolio_vol_components[, 1])) %>%
    hc_add_series(portfolio_vol_components[, 2], 
                  name = names(portfolio_vol_components[, 2])) %>%
    hc_add_series(portfolio_vol_components[, 3], 
                  name = names(portfolio_vol_components[, 3])) %>%
    hc_add_series(portfolio_vol_components[, 4], 
                  name = names(portfolio_vol_components[, 4])) %>% 
    hc_add_series(portfolio_vol_components[, 5], 
                  name = names(portfolio_vol_components[, 5])) %>% 
    hc_add_theme(hc_theme_flat()) %>% 
    hc_yAxis(
      labels = list(format = "{value}%"), 
             opposite = FALSE, 
             min = min(portfolio_vol_components) -5,
             max = max(portfolio_vol_components) + 5) %>%
    hc_navigator(enabled = FALSE) %>% 
    hc_scrollbar(enabled = FALSE)
})
```

### Stacked Area Chart

```{r}
renderHighchart({
  portfolio_vol_components <- 
    portfolio_vol_components_xts()
  
 highchart() %>% 
  hc_chart(type = "area") %>% 
  hc_title(text = "Stacked Volatility Contribution") %>%
  hc_plotOptions(area = list(
     stacking = "percent",
     lineColor = "#ffffff",
     lineWidth = 1,
     marker = list(
       lineWidth = 1,
       lineColor = "#ffffff"
       ))
     ) %>% 
    hc_add_series(portfolio_vol_components[, 1], 
                  name = names(portfolio_vol_components[, 1])) %>%
    hc_add_series(portfolio_vol_components[, 2], 
                  name = names(portfolio_vol_components[, 2])) %>%
    hc_add_series(portfolio_vol_components[, 3], 
                  name = names(portfolio_vol_components[, 3])) %>%
    hc_add_series(portfolio_vol_components[, 4], 
                  name = names(portfolio_vol_components[, 4])) %>% 
    hc_add_series(portfolio_vol_components[, 5], 
                  name = names(portfolio_vol_components[, 5])) %>% 
     hc_yAxis(labels = list(format = "{value}%"),
      opposite = FALSE) %>%
  hc_xAxis(type = "datetime") %>%
  hc_tooltip(pointFormat = 
"
{series.name}:{point.percentage:.1f}%",
             shared = TRUE) %>% 
  hc_navigator(enabled = FALSE) %>% 
  hc_scrollbar(enabled = FALSE) %>% 
  hc_add_theme(hc_theme_flat()) %>%
  hc_exporting(enabled = TRUE) %>% 
  hc_legend(enabled = TRUE)
})
```


Row
------------------------


### bar chart with weights

```{r}
renderPlot(
  percentages_tibble_pre_built() %>% 
  gather(type, percent, -asset) %>% 
  group_by(type) %>% 
  mutate(percent = percent/100) %>% 
  ggplot(aes(x = asset, y = percent, fill = type)) +
  geom_col(position = 'dodge') + 
  scale_y_continuous(labels = percent) + 
  ggtitle("Percent Contribution to Volatility") +
  theme(plot.title = element_text(hjust = 0.5))
)
```